In [11]:
source("inst/scripts/download_national_data.R")
download_national_data()

Downloading...
All data is approx 14GB...
  |                                                                      |   0%File already exists: raw_data/national_rtt/time_series//RTT-Overview-Timeseries-Including-Estimates-for-Missing-Trusts-Jul25-XLS-114K-92707.xlsx
  |===================================                                   |  50% (50.0%)
File already exists: raw_data/national_rtt/time_series//RTT-Overview-Timeseries-Jun15-revised-XLS-107K-92612.xls
  |======================================================================| 100% (100.0%)

[1] "Downloading CSV files..."
  |                                                                      |   0%Downloading https://www.england.nhs.uk/statistics/wp-content/uploads/sites/2/2025/09/Full-CSV-data-file-Jul25-ZIP-4M-92707.zip to raw_data/national_rtt/csv//Full-CSV-data-file-Jul25-ZIP-4M-92707.zip
  |=                                                                     |   1% (0.8%)
Downloading https://www.england.nhs.uk/statistics/wp-content/uploads/sites/2/2025/08/Full-CSV-data-file-Jun25-ZIP-4M-94367.zip to raw_data/national_rtt/csv//Full-CSV-data-file-Jun25-ZIP-4M-94367.zip
  |=                                                                     |   2% (1.7%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-May25-ZIP-4M-32711.zip
  |==                                                                    |   3% (2.5%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Apr25-ZIP-4M-77252.zip
 (3.4%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Mar25-ZIP-4M-revised.zip
  |===                                                                   |   4% (4.2%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Feb25-ZIP-4M-revised.zip
  |====                                                                  |   5% (5.1%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Jan25-ZIP-4M-revised.zip
  |====                                                                  |   6% (5.9%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Dec24-ZIP-4M-revised.zip
  |=====                                                                 |   7% (6.8%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Nov24-ZIP-4M-revised.zip
  |=====                                                                 |   8% (7.6%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Oct24-ZIP-4M-revised.zip
  |======                                                                |   8% (8.5%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Sep24-ZIP-4M-revised.zip
  |=======                                                               |   9% (9.3%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Aug24-ZIP-4M-revised.zip
  |=======                                                               |  10% (10.2%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Jul24-ZIP-4M-revised.zip
  |========                                                              |  11% (11.0%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Jun24-ZIP-4M-revised.zip
  |========                                                              |  12% (11.9%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-May24-ZIP-4M-revised.zip
  |=========                                                             |  13% (12.7%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Apr24-ZIP-4M-revised.zip
  |=========                                                             |  14% (13.6%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Mar24-ZIP-3832K-revised.zip
  |==========                                                            |  14% (14.4%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Feb24-ZIP-3881K-revised.zip
  |===========                                                           |  15% (15.3%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Jan24-ZIP-3943K-revised.zip
  |===========                                                           |  16% (16.1%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Dec23-ZIP-3800K-revised.zip
  |============                                                          |  17% (16.9%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Nov23-ZIP-3952K-revised.zip
  |============                                                          |  18% (17.8%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Oct23-ZIP-3928K-revised.zip
  |=============                                                         |  19% (18.6%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Sep23-ZIP-3654K-revised.zip
  |==============                                                        |  19% (19.5%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Aug23-ZIP-3646K-revised.zip
  |==============                                                        |  20% (20.3%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Jul23-ZIP-3623K-revised.zip
  |===============                                                       |  21% (21.2%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Jun23-ZIP-3659K-64970.zip
  |===============                                                       |  22% (22.0%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-May23-ZIP-3627K-revised.zip
  |================                                                      |  23% (22.9%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Apr23-ZIP-3528K-36960.zip
  |=================                                                     |  24% (23.7%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Mar23-revised-ZIP-3589K.zip
  |=================                                                     |  25% (24.6%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Feb23-revised-ZIP-3784K.zip
  |==================                                                    |  25% (25.4%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Jan23-revised-ZIP-3609K.zip
  |==================                                                    |  26% (26.3%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Dec22-revised-ZIP-3631K.zip
  |===================                                                   |  27% (27.1%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Nov22-revised-ZIP-3508K.zip
  |====================                                                  |  28% (28.0%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Oct22-revised-ZIP-3473K.zip
  |====================                                                  |  29% (28.8%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Sep22-revised-ZIP-3542K.zip
  |=====================                                                 |  30% (29.7%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Aug22-revised-ZIP-3488K.zip
  |=====================                                                 |  31% (30.5%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Jul22-revised-ZIP-3642K.zip
  |======================                                                |  31% (31.4%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Jun22-revised-ZIP-4253.zip
  |=======================                                               |  32% (32.2%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-May22-revised-ZIP-4392K.zip
  |=======================                                               |  33% (33.1%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Apr22-revised-ZIP-4253.zip
  |========================                                              |  34% (33.9%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Mar22-revised-ZIP-111805K.zip
  |========================                                              |  35% (34.7%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Feb22-revised-ZIP-109268K.zip
  |=========================                                             |  36% (35.6%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Jan22-revised-ZIP-4266K.zip
  |==========================                                            |  36% (36.4%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Dec21-revised-ZIP-3744K.zip
  |==========================                                            |  37% (37.3%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Nov21-revised-ZIP-3826K.zip
  |===========================                                           |  38% (38.1%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Oct21-revised-ZIP-3787K.zip
  |===========================                                           |  39% (39.0%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Sep21-revised-ZIP-3768K.zip
  |============================                                          |  40% (39.8%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Aug21-revised-ZIP-3682K.zip
  |============================                                          |  41% (40.7%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Jul21-revised-ZIP-3710K.zip
  |=============================                                         |  42% (41.5%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Jun21-revised-ZIP-3739K.zip
  |==============================                                        |  42% (42.4%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-May21-revised-ZIP-3656K.zip
  |==============================                                        |  43% (43.2%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Apr21-revised-ZIP-3587K.zip
  |===============================                                       |  44% (44.1%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Mar21-ZIP-2888K-76325.zip
  |===============================                                       |  45% (44.9%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Feb21-ZIP-2739K-25692.zip
  |================================                                      |  46% (45.8%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Jan21-ZIP-2714K-24158.zip
  |=================================                                     |  47% (46.6%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Dec20-revised-ZIP-2860K.zip
 (47.5%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Nov20-ZIP-2758K-26885.zip
  |==================================                                    |  48% (48.3%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Oct20-revised-ZIP-2772K.zip
  |==================================                                    |  49% (49.2%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Sep20-ZIP-2738K-20720.zip
  |===================================                                   |  50% (50.0%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Aug20-ZIP-2594K-09869.zip
  |====================================                                  |  51% (50.8%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Jul20-ZIP-2546K.zip
  |====================================                                  |  52% (51.7%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Jun20-revised-ZIP-2649K.zip
  |=====================================                                 |  53% (52.5%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-May20-revised-ZIP-2216K.zip
 (53.4%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Apr20-revised-ZIP-2295K.zip
  |======================================                                |  54% (54.2%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Mar20-ZIP-2995K-73640.zip
  |=======================================                               |  55% (55.1%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Feb20-revised-ZIP-3171K.zip
  |=======================================                               |  56% (55.9%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Jan20-revised-ZIP-3227K.zip
  |========================================                              |  57% (56.8%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Dec19-revised-ZIP-3109K.zip
  |========================================                              |  58% (57.6%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Nov19-revised-ZIP-3528K.zip
  |=========================================                             |  58% (58.5%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Oct19-revised-ZIP-3580K.zip
  |==========================================                            |  59% (59.3%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Sep19-ZIP-3532K-62303.zip
  |==========================================                            |  60% (60.2%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Aug19-ZIP-3493K-revised.zip
  |===========================================                           |  61% (61.0%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Jul19-ZIP-3550K-revised.zip
  |===========================================                           |  62% (61.9%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Jun19-ZIP-3502K.zip
  |============================================                          |  63% (62.7%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-May19-ZIP-3497K-revised.zip
  |============================================                          |  64% (63.6%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Apr19-ZIP-3436K-revised.zip
  |=============================================                         |  64% (64.4%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Mar19-revised-ZIP-3506K.zip
  |==============================================                        |  65% (65.3%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Feb19-revised-ZIP-3485K.zip
  |==============================================                        |  66% (66.1%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Jan19-revised-ZIP-3634K.zip
  |===============================================                       |  67% (66.9%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Dec18-ZIP-3427K.zip
  |===============================================                       |  68% (67.8%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Nov18-revised-ZIP-3544K.zip
  |================================================                      |  69% (68.6%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Oct18-revised-ZIP-3574K.zip
  |=================================================                     |  69% (69.5%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Sep18-revised-ZIP-K.zip
  |=================================================                     |  70% (70.3%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Aug18-revised-ZIP-3464K.zip
  |==================================================                    |  71% (71.2%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Jul18-revised-ZIP-3450K.zip
  |==================================================                    |  72% (72.0%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Jun18-revised-ZIP-3426K.zip
  |===================================================                   |  73% (72.9%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-May18-revised-ZIP-3424K.zip
  |====================================================                  |  74% (73.7%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Apr18-revised-ZIP-3380K.zip
  |====================================================                  |  75% (74.6%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Mar18-revised-ZIP-3051K.zip
  |=====================================================                 |  75% (75.4%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Feb18-revised-ZIP-3032K.zip
  |=====================================================                 |  76% (76.3%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Jan18-revised-v2-ZIP-3086K.zip
  |======================================================                |  77% (77.1%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Dec17-revised-v2-ZIP-3135K.zip
  |=======================================================               |  78% (78.0%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Nov17-revised-v2-ZIP-3058K.zip
  |=======================================================               |  79% (78.8%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Oct17-revised-v2-ZIP-3084K.zip
  |========================================================              |  80% (79.7%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Sep17-ZIP-3092K-98673.zip
  |========================================================              |  81% (80.5%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Aug17-revised-ZIP-3103K.zip
  |=========================================================             |  81% (81.4%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Jul17-revised-ZIP-3083K.zip
  |==========================================================            |  82% (82.2%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Jun17-revised-ZIP-3092K.zip
  |==========================================================            |  83% (83.1%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-May17-revised-ZIP-3077K.zip
  |===========================================================           |  84% (83.9%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Apr17-revised-ZIP-2963K.zip
  |===========================================================           |  85% (84.7%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Mar17-revised-ZIP-2872K.zip
  |============================================================          |  86% (85.6%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Feb17-revised-ZIP-2815K.zip
  |=============================================================         |  86% (86.4%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Jan17-revised-ZIP-2839K.zip
  |=============================================================         |  87% (87.3%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Dec16-revised-ZIP-2753K.zip
  |==============================================================        |  88% (88.1%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Nov16-revised-ZIP-2856K.zip
  |==============================================================        |  89% (89.0%)
File already exists: raw_data/national_rtt/csv//Full-CSV-data-file-Oct16-revised-ZIP-2826K.zip
  |===============================================================       |  90% (89.8%)

In [26]:
source("inst/scripts/process_national_data.R")
all <- load_national_incomplete(reload = FALSE, start_date = as.Date("1900-01-01"), end_date = as.Date("2100-12-31"))

In [ ]:
source("inst/scripts/national_incomplete_stats.R")
process_incomplete_stats()

        Region_Code Provider_Code Provider_Name
1       Y56         R1H           BARTS HEALTH NHS TRUST
2       Y56         R1H           BARTS HEALTH NHS TRUST
3       Y56         R1H           BARTS HEALTH NHS TRUST
4       Y56         R1H           BARTS HEALTH NHS TRUST
5       Y56         R1H           BARTS HEALTH NHS TRUST
6       Y56         R1H           BARTS HEALTH NHS TRUST
7       Y56         R1H           BARTS HEALTH NHS TRUST
8       Y56         R1H           BARTS HEALTH NHS TRUST
9       Y56         R1H           BARTS HEALTH NHS TRUST
10      Y56         R1H           BARTS HEALTH NHS TRUST
11      Y56         R1H           BARTS HEALTH NHS TRUST
12      Y56         R1H           BARTS HEALTH NHS TRUST
13      Y56         R1H           BARTS HEALTH NHS TRUST
14      Y56         R1H           BARTS HEALTH NHS TRUST
15      Y56         R1H           BARTS HEALTH NHS TRUST
16      Y56         R1H           BARTS HEALTH NHS TRUST
17      Y56         R1H           BARTS HEALTH NHS TRUST
18      Y56         R1H           BARTS HEALTH NHS TRUST
19      Y56         R1H           BARTS HEALTH NHS TRUST
20      Y56         R1H           BARTS HEALTH NHS TRUST
21      Y56         R1H           BARTS HEALTH NHS TRUST
22      Y56         R1H           BARTS HEALTH NHS TRUST
23      Y56         R1H           BARTS HEALTH NHS TRUST
24      Y56         R1H           BARTS HEALTH NHS TRUST
25      Y56         R1H           BARTS HEALTH NHS TRUST
26      Y56         R1H           BARTS HEALTH NHS TRUST
27      Y56         R1H           BARTS HEALTH NHS TRUST
28      Y56         R1H           BARTS HEALTH NHS TRUST
29      Y56         R1H           BARTS HEALTH NHS TRUST
30      Y56         R1H           BARTS HEALTH NHS TRUST
⋮       ⋮           ⋮             ⋮
1149091 Y63         TAD           BRADFORD DISTRICT CARE NHS FOUNDATION TRUST
1149092 Y63         TAD           BRADFORD DISTRICT CARE NHS FOUNDATION TRUST
1149093 Y63         TAD           BRADFORD DISTRICT CARE NHS FOUNDATION TRUST
1149094 Y63         TAD           BRADFORD DISTRICT CARE NHS FOUNDATION TRUST
1149095 Y63         TAD           BRADFORD DISTRICT CARE NHS FOUNDATION TRUST
1149096 Y63         TAD           BRADFORD DISTRICT CARE NHS FOUNDATION TRUST
1149097 Y63         TAD           BRADFORD DISTRICT CARE NHS FOUNDATION TRUST
1149098 Y63         TAD           BRADFORD DISTRICT CARE NHS FOUNDATION TRUST
1149099 Y63         TAD           BRADFORD DISTRICT CARE NHS FOUNDATION TRUST
1149100 Y63         TAD           BRADFORD DISTRICT CARE NHS FOUNDATION TRUST
1149101 Y63         TAD           BRADFORD DISTRICT CARE NHS FOUNDATION TRUST
1149102 Y63         TAD           BRADFORD DISTRICT CARE NHS FOUNDATION TRUST
1149103 Y63         TAD           BRADFORD DISTRICT CARE NHS FOUNDATION TRUST
1149104 Y63         TAD           BRADFORD DISTRICT CARE NHS FOUNDATION TRUST
1149105 Y63         TAD           BRADFORD DISTRICT CARE NHS FOUNDATION TRUST
1149106 Y63         TAD           BRADFORD DISTRICT CARE NHS FOUNDATION TRUST
1149107 Y63         TAD           BRADFORD DISTRICT CARE NHS FOUNDATION TRUST
1149108 Y63         TAD           BRADFORD DISTRICT CARE NHS FOUNDATION TRUST
1149109 Y63         TAD           BRADFORD DISTRICT CARE NHS FOUNDATION TRUST
1149110 Y63         TAD           BRADFORD DISTRICT CARE NHS FOUNDATION TRUST
1149111 Y63         TAD           BRADFORD DISTRICT CARE NHS FOUNDATION TRUST
1149112 Y63         TAD           BRADFORD DISTRICT CARE NHS FOUNDATION TRUST
1149113 Y63         TAD           BRADFORD DISTRICT CARE NHS FOUNDATION TRUST
1149114 Y63         TAD           BRADFORD DISTRICT CARE NHS FOUNDATION TRUST
1149115 Y63         TAD           BRADFORD DISTRICT CARE NHS FOUNDATION TRUST
1149116 Y63         TAD           BRADFORD DISTRICT CARE NHS FOUNDATION TRUST
1149117 Y63         TAD           BRADFORD DISTRICT CARE NHS FOUNDATION TRUST
1149118 Y63         TAD           BRADFORD DISTRICT CARE NHS FOUNDATION TRUST
1149119 Y63         TAD           BRADFORD DISTRICT CARE NHS FOUNDATION TRUST
1149120 Y63         TAD           BRADFORD DISTRICT CARE NHS FOUNDATION TRUST
        Treatment_Function_Code Treatment_Function      n   report_date
1       C_100                   General Surgery Service 239 2025-04-30
2       C_100                   General Surgery Service 103 2025-04-30
3       C_100                   General Surgery Service 160 2025-04-30
4       C_100                   General Surgery Service 165 2025-04-30
5       C_100                   General Surgery Service 172 2025-04-30
6       C_100                   General Surgery Service 159 2025-04-30
7       C_100                   General Surgery Service 141 2025-04-30
8       C_100                   General Surgery Service 130 2025-04-30
9       C_100                   General Surgery Service 159 2025-04-30
10      C_100                   General Surgery Service 122 2025-04-30
11      C_100                   General Surgery Service 128 2025-04-30
12      C_100                   General Surgery Service 134 2025-04-30
13      C_100                   General Surgery Service 137 2025-04-30
14      C_100                   General Surgery Service 105 2025-04-30
15      C_100                   General Surgery Service  88 2025-04-30
16      C_100                   General Surgery Service 109 2025-04-30
17      C_100                   General Surgery Service  77 2025-04-30
18      C_100                   General Surgery Service  58 2025-04-30
19      C_100                   General Surgery Service 107 2025-04-30
20      C_100                   General Surgery Service  89 2025-04-30
21      C_100                   General Surgery Service  70 2025-04-30
22      C_100                   General Surgery Service  71 2025-04-30
23      C_100                   General Surgery Service  98 2025-04-30
24      C_100                   General Surgery Service  83 2025-04-30
25      C_100                   General Surgery Service  87 2025-04-30
26      C_100                   General Surgery Service  81 2025-04-30
27      C_100                   General Surgery Service  65 2025-04-30
28      C_100                   General Surgery Service  85 2025-04-30
29      C_100                   General Surgery Service  66 2025-04-30
30      C_100                   General Surgery Service  65 2025-04-30
⋮       ⋮                       ⋮                       ⋮   ⋮
1149091 C_999                   Total                   0   2025-05-31
1149092 C_999                   Total                   0   2025-05-31
1149093 C_999                   Total                   0   2025-05-31
1149094 C_999                   Total                   0   2025-05-31
1149095 C_999                   Total                   0   2025-05-31
1149096 C_999                   Total                   0   2025-05-31
1149097 C_999                   Total                   0   2025-05-31
1149098 C_999                   Total                   0   2025-05-31
1149099 C_999                   Total                   0   2025-05-31
1149100 C_999                   Total                   0   2025-05-31
1149101 C_999                   Total                   0   2025-05-31
1149102 C_999                   Total                   0   2025-05-31
1149103 C_999                   Total                   0   2025-05-31
1149104 C_999                   Total                   0   2025-05-31
1149105 C_999                   Total                   0   2025-05-31
1149106 C_999                   Total                   0   2025-05-31
1149107 C_999                   Total                   0   2025-05-31
1149108 C_999                   Total                   0   2025-05-31
1149109 C_999                   Total                   0   2025-05-31
1149110 C_999                   Total                   0   2025-05-31
1149111 C_999                   Total                   0   2025-05-31
1149112 C_999                   Total                   0   2025-05-31
1149113 C_999                   Total                   0   2025-05-31
1149114 C_999                   Total                   0   2025-05-31
1149115 C_999                   Total                   0   2025-05-31
1149116 C_999                   Total                   0   2025-05-31
1149117 C_999                   Total                   0   2025-05-31
1149118 C_999                   Total                   0   2025-05-31
1149119 C_999                   Total                   0   2025-05-31
1149120 C_999                   Total                   0   2025-05-31
        arrived_since arrived_before
1       2025-04-24    2025-04-30
2       2025-04-17    2025-04-23
3       2025-04-10    2025-04-16
4       2025-04-03    2025-04-09
5       2025-03-27    2025-04-02
6       2025-03-20    2025-03-26
7       2025-03-13    2025-03-19
8       2025-03-06    2025-03-12
9       2025-02-27    2025-03-05
10      2025-02-20    2025-02-26
11      2025-02-13    2025-02-19
12      2025-02-06    2025-02-12
13      2025-01-30    2025-02-05
14      2025-01-23    2025-01-29
15      2025-01-16    2025-01-22
16      2025-01-09    2025-01-15
17      2025-01-02    2025-01-08
18      2024-12-26    2025-01-01
19      2024-12-19    2024-12-25
20      2024-12-12    2024-12-18
21      2024-12-05    2024-12-11
22      2024-11-28    2024-12-04
23      2024-11-21    2024-11-27
24      2024-11-14    2024-11-20
25      2024-11-07    2024-11-13
26      2024-10-31    2024-11-06
27      2024-10-24    2024-10-30
28      2024-10-17    2024-10-23
29      2024-10-10    2024-10-16
30      2024-10-03    2024-10-09
⋮       ⋮             ⋮
1149091 2023-12-17    2023-12-23
1149092 2023-12-10    2023-12-16
1149093 2023-12-03    2023-12-09
1149094 2023-11-26    2023-12-02
1149095 2023-11-19    2023-11-25
1149096 2023-11-12    2023-11-18
1149097 2023-11-05    2023-11-11
1149098 2023-10-29    2023-11-04
1149099 2023-10-22    2023-10-28
1149100 2023-10-15    2023-10-21
1149101 2023-10-08    2023-10-14
1149102 2023-10-01    2023-10-07
1149103 2023-09-24    2023-09-30
1149104 2023-09-17    2023-09-23
1149105 2023-09-10    2023-09-16
1149106 2023-09-03    2023-09-09
1149107 2023-08-27    2023-09-02
1149108 2023-08-20    2023-08-26
1149109 2023-08-13    2023-08-19
1149110 2023-08-06    2023-08-12
1149111 2023-07-30    2023-08-05
1149112 2023-07-23    2023-07-29
1149113 2023-07-16    2023-07-22
1149114 2023-07-09    2023-07-15
1149115 2023-07-02    2023-07-08
1149116 2025-03-16    2025-03-22
1149117 2025-03-16    2025-03-22
1149118 2025-03-16    2025-03-22
1149119 2025-03-16    2025-03-22
1149120 2025-03-16    2025-03-22

In [21]:
View(all_national_incomplete)

        Region_Code Provider_Code Provider_Name
1       Y56         R1H           BARTS HEALTH NHS TRUST
2       Y56         R1H           BARTS HEALTH NHS TRUST
3       Y56         R1H           BARTS HEALTH NHS TRUST
4       Y56         R1H           BARTS HEALTH NHS TRUST
5       Y56         R1H           BARTS HEALTH NHS TRUST
6       Y56         R1H           BARTS HEALTH NHS TRUST
7       Y56         R1H           BARTS HEALTH NHS TRUST
8       Y56         R1H           BARTS HEALTH NHS TRUST
9       Y56         R1H           BARTS HEALTH NHS TRUST
10      Y56         R1H           BARTS HEALTH NHS TRUST
11      Y56         R1H           BARTS HEALTH NHS TRUST
12      Y56         R1H           BARTS HEALTH NHS TRUST
13      Y56         R1H           BARTS HEALTH NHS TRUST
14      Y56         R1H           BARTS HEALTH NHS TRUST
15      Y56         R1H           BARTS HEALTH NHS TRUST
16      Y56         R1H           BARTS HEALTH NHS TRUST
17      Y56         R1H           BARTS HEALTH NHS TRUST
18      Y56         R1H           BARTS HEALTH NHS TRUST
19      Y56         R1H           BARTS HEALTH NHS TRUST
20      Y56         R1H           BARTS HEALTH NHS TRUST
21      Y56         R1H           BARTS HEALTH NHS TRUST
22      Y56         R1H           BARTS HEALTH NHS TRUST
23      Y56         R1H           BARTS HEALTH NHS TRUST
24      Y56         R1H           BARTS HEALTH NHS TRUST
25      Y56         R1H           BARTS HEALTH NHS TRUST
26      Y56         R1H           BARTS HEALTH NHS TRUST
27      Y56         R1H           BARTS HEALTH NHS TRUST
28      Y56         R1H           BARTS HEALTH NHS TRUST
29      Y56         R1H           BARTS HEALTH NHS TRUST
30      Y56         R1H           BARTS HEALTH NHS TRUST
⋮       ⋮           ⋮             ⋮
1149091 Y63         TAD           BRADFORD DISTRICT CARE NHS FOUNDATION TRUST
1149092 Y63         TAD           BRADFORD DISTRICT CARE NHS FOUNDATION TRUST
1149093 Y63         TAD           BRADFORD DISTRICT CARE NHS FOUNDATION TRUST
1149094 Y63         TAD           BRADFORD DISTRICT CARE NHS FOUNDATION TRUST
1149095 Y63         TAD           BRADFORD DISTRICT CARE NHS FOUNDATION TRUST
1149096 Y63         TAD           BRADFORD DISTRICT CARE NHS FOUNDATION TRUST
1149097 Y63         TAD           BRADFORD DISTRICT CARE NHS FOUNDATION TRUST
1149098 Y63         TAD           BRADFORD DISTRICT CARE NHS FOUNDATION TRUST
1149099 Y63         TAD           BRADFORD DISTRICT CARE NHS FOUNDATION TRUST
1149100 Y63         TAD           BRADFORD DISTRICT CARE NHS FOUNDATION TRUST
1149101 Y63         TAD           BRADFORD DISTRICT CARE NHS FOUNDATION TRUST
1149102 Y63         TAD           BRADFORD DISTRICT CARE NHS FOUNDATION TRUST
1149103 Y63         TAD           BRADFORD DISTRICT CARE NHS FOUNDATION TRUST
1149104 Y63         TAD           BRADFORD DISTRICT CARE NHS FOUNDATION TRUST
1149105 Y63         TAD           BRADFORD DISTRICT CARE NHS FOUNDATION TRUST
1149106 Y63         TAD           BRADFORD DISTRICT CARE NHS FOUNDATION TRUST
1149107 Y63         TAD           BRADFORD DISTRICT CARE NHS FOUNDATION TRUST
1149108 Y63         TAD           BRADFORD DISTRICT CARE NHS FOUNDATION TRUST
1149109 Y63         TAD           BRADFORD DISTRICT CARE NHS FOUNDATION TRUST
1149110 Y63         TAD           BRADFORD DISTRICT CARE NHS FOUNDATION TRUST
1149111 Y63         TAD           BRADFORD DISTRICT CARE NHS FOUNDATION TRUST
1149112 Y63         TAD           BRADFORD DISTRICT CARE NHS FOUNDATION TRUST
1149113 Y63         TAD           BRADFORD DISTRICT CARE NHS FOUNDATION TRUST
1149114 Y63         TAD           BRADFORD DISTRICT CARE NHS FOUNDATION TRUST
1149115 Y63         TAD           BRADFORD DISTRICT CARE NHS FOUNDATION TRUST
1149116 Y63         TAD           BRADFORD DISTRICT CARE NHS FOUNDATION TRUST
1149117 Y63         TAD           BRADFORD DISTRICT CARE NHS FOUNDATION TRUST
1149118 Y63         TAD           BRADFORD DISTRICT CARE NHS FOUNDATION TRUST
1149119 Y63         TAD           BRADFORD DISTRICT CARE NHS FOUNDATION TRUST
1149120 Y63         TAD           BRADFORD DISTRICT CARE NHS FOUNDATION TRUST
        Treatment_Function_Code Treatment_Function      n   report_date
1       C_100                   General Surgery Service 239 2025-04-30
2       C_100                   General Surgery Service 103 2025-04-30
3       C_100                   General Surgery Service 160 2025-04-30
4       C_100                   General Surgery Service 165 2025-04-30
5       C_100                   General Surgery Service 172 2025-04-30
6       C_100                   General Surgery Service 159 2025-04-30
7       C_100                   General Surgery Service 141 2025-04-30
8       C_100                   General Surgery Service 130 2025-04-30
9       C_100                   General Surgery Service 159 2025-04-30
10      C_100                   General Surgery Service 122 2025-04-30
11      C_100                   General Surgery Service 128 2025-04-30
12      C_100                   General Surgery Service 134 2025-04-30
13      C_100                   General Surgery Service 137 2025-04-30
14      C_100                   General Surgery Service 105 2025-04-30
15      C_100                   General Surgery Service  88 2025-04-30
16      C_100                   General Surgery Service 109 2025-04-30
17      C_100                   General Surgery Service  77 2025-04-30
18      C_100                   General Surgery Service  58 2025-04-30
19      C_100                   General Surgery Service 107 2025-04-30
20      C_100                   General Surgery Service  89 2025-04-30
21      C_100                   General Surgery Service  70 2025-04-30
22      C_100                   General Surgery Service  71 2025-04-30
23      C_100                   General Surgery Service  98 2025-04-30
24      C_100                   General Surgery Service  83 2025-04-30
25      C_100                   General Surgery Service  87 2025-04-30
26      C_100                   General Surgery Service  81 2025-04-30
27      C_100                   General Surgery Service  65 2025-04-30
28      C_100                   General Surgery Service  85 2025-04-30
29      C_100                   General Surgery Service  66 2025-04-30
30      C_100                   General Surgery Service  65 2025-04-30
⋮       ⋮                       ⋮                       ⋮   ⋮
1149091 C_999                   Total                   0   2025-05-31
1149092 C_999                   Total                   0   2025-05-31
1149093 C_999                   Total                   0   2025-05-31
1149094 C_999                   Total                   0   2025-05-31
1149095 C_999                   Total                   0   2025-05-31
1149096 C_999                   Total                   0   2025-05-31
1149097 C_999                   Total                   0   2025-05-31
1149098 C_999                   Total                   0   2025-05-31
1149099 C_999                   Total                   0   2025-05-31
1149100 C_999                   Total                   0   2025-05-31
1149101 C_999                   Total                   0   2025-05-31
1149102 C_999                   Total                   0   2025-05-31
1149103 C_999                   Total                   0   2025-05-31
1149104 C_999                   Total                   0   2025-05-31
1149105 C_999                   Total                   0   2025-05-31
1149106 C_999                   Total                   0   2025-05-31
1149107 C_999                   Total                   0   2025-05-31
1149108 C_999                   Total                   0   2025-05-31
1149109 C_999                   Total                   0   2025-05-31
1149110 C_999                   Total                   0   2025-05-31
1149111 C_999                   Total                   0   2025-05-31
1149112 C_999                   Total                   0   2025-05-31
1149113 C_999                   Total                   0   2025-05-31
1149114 C_999                   Total                   0   2025-05-31
1149115 C_999                   Total                   0   2025-05-31
1149116 C_999                   Total                   0   2025-05-31
1149117 C_999                   Total                   0   2025-05-31
1149118 C_999                   Total                   0   2025-05-31
1149119 C_999                   Total                   0   2025-05-31
1149120 C_999                   Total                   0   2025-05-31
        arrived_since arrived_before
1       2025-04-24    2025-04-30
2       2025-04-17    2025-04-23
3       2025-04-10    2025-04-16
4       2025-04-03    2025-04-09
5       2025-03-27    2025-04-02
6       2025-03-20    2025-03-26
7       2025-03-13    2025-03-19
8       2025-03-06    2025-03-12
9       2025-02-27    2025-03-05
10      2025-02-20    2025-02-26
11      2025-02-13    2025-02-19
12      2025-02-06    2025-02-12
13      2025-01-30    2025-02-05
14      2025-01-23    2025-01-29
15      2025-01-16    2025-01-22
16      2025-01-09    2025-01-15
17      2025-01-02    2025-01-08
18      2024-12-26    2025-01-01
19      2024-12-19    2024-12-25
20      2024-12-12    2024-12-18
21      2024-12-05    2024-12-11
22      2024-11-28    2024-12-04
23      2024-11-21    2024-11-27
24      2024-11-14    2024-11-20
25      2024-11-07    2024-11-13
26      2024-10-31    2024-11-06
27      2024-10-24    2024-10-30
28      2024-10-17    2024-10-23
29      2024-10-10    2024-10-16
30      2024-10-03    2024-10-09
⋮       ⋮             ⋮
1149091 2023-12-17    2023-12-23
1149092 2023-12-10    2023-12-16
1149093 2023-12-03    2023-12-09
1149094 2023-11-26    2023-12-02
1149095 2023-11-19    2023-11-25
1149096 2023-11-12    2023-11-18
1149097 2023-11-05    2023-11-11
1149098 2023-10-29    2023-11-04
1149099 2023-10-22    2023-10-28
1149100 2023-10-15    2023-10-21
1149101 2023-10-08    2023-10-14
1149102 2023-10-01    2023-10-07
1149103 2023-09-24    2023-09-30
1149104 2023-09-17    2023-09-23
1149105 2023-09-10    2023-09-16
1149106 2023-09-03    2023-09-09
1149107 2023-08-27    2023-09-02
1149108 2023-08-20    2023-08-26
1149109 2023-08-13    2023-08-19
1149110 2023-08-06    2023-08-12
1149111 2023-07-30    2023-08-05
1149112 2023-07-23    2023-07-29
1149113 2023-07-16    2023-07-22
1149114 2023-07-09    2023-07-15
1149115 2023-07-02    2023-07-08
1149116 2025-03-16    2025-03-22
1149117 2025-03-16    2025-03-22
1149118 2025-03-16    2025-03-22
1149119 2025-03-16    2025-03-22
1149120 2025-03-16    2025-03-22